from django import forms
from .models import UserProfile
from pods.models import Category


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = ("user", "pro_user", "profile_image_file")

    def __init__(self, *args, **kwargs):
        """ Add placeholders and classes, remove autogenerated labels. """
        super().__init__(*args, **kwargs)
        categories = Category.objects.all()
        friendly_names = [(c.id, c.get_friendly_name()) for c in categories]
        placeholders = {
            "nickname": "What should we call you",
            "bio": "Tell us about yourself",
            "location": "Tell us where you are",
            "birth_date": "Date of birth",
            "profile_image_url": "Load your profile image from a URL (e.g. Imgur)",
            "profile_image_file": "Upload a local image file (max size: 10Mb)",
        }

        self.fields['fav_genre'].choices = friendly_names
        for field in self.fields:
            if field != "fav_genre":
                placeholder = placeholders[field]
                self.fields[field].widget.attrs["placeholder"] = placeholder
            self.fields[field].widget.attrs["class"] = "profile-form-field"
            self.fields["birth_date"].widget = forms.DateInput(attrs={"type": "date"})
            if field == "bio":
                self.fields[field].widget.attrs["class"] += " profile-modal-textbox"

