# Generated by Django 3.0.8 on 2020-07-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='podcast_id',
            new_name='podcast',
        ),
    ]
