# Generated by Django 3.0.8 on 2020-07-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200723_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
