# Generated by Django 3.0.8 on 2020-07-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pods', '0015_auto_20200725_2006'),
        ('home', '0004_userprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fav_genre',
            field=models.ManyToManyField(blank=True, to='pods.Category', verbose_name='Favourite Genres'),
        ),
    ]
