# Generated by Django 3.0.8 on 2020-07-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(editable=False, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(editable=False, max_length=40)),
                ('postcode', models.CharField(editable=False, max_length=20)),
                ('town_or_city', models.CharField(editable=False, max_length=40)),
                ('street_address1', models.CharField(editable=False, max_length=80)),
                ('street_address2', models.CharField(editable=False, max_length=80)),
                ('county', models.CharField(editable=False, max_length=80)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
