# Generated by Django 3.0.8 on 2020-07-29 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_auto_20200729_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='country',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='county',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='postcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='street_address1',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='street_address2',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='town_or_city',
            field=models.CharField(max_length=40),
        ),
    ]
