# Generated by Django 3.0.8 on 2020-07-30 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0004_auto_20200729_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='username',
            new_name='user',
        ),
    ]
